"use client";

// QRCode: receive-address display (component-gaps Batch 3 deferred).
// Composition tier (same as PriceChart): depends on the `qrcode` npm
// package, so it lives outside src/design-system/ and is exempt from
// check:portable / the copy-in registry. Composes CIDS AddressChip for
// truncation + copy + optional explorer link. SVG fills are rewritten
// to CSS variables so theme flips (dark/mono/light/violet) recolor the
// matrix without regenerating.

import { useEffect, useState } from "react";
import QRCodeLib from "qrcode";
import { cn } from "@/lib/utils";
import { AddressChip } from "@/design-system";

function themeSvg(raw: string): string {
  // qrcode emits #ffffff quiet-zone fill + #000000 module strokes.
  // Map to tokens so ThemeToggle restyles live.
  return raw
    .replace(/fill="#ffffff"/gi, 'fill="var(--surface-bright)"')
    .replace(/stroke="#000000"/gi, 'stroke="currentColor"');
}

export function QRCode({
  value,
  size = 160,
  label = "Scan to send",
  explorerHref,
  className,
  "aria-label": ariaLabel,
}: {
  /** Payload encoded in the matrix: typically a wallet/mint address. */
  value: string;
  /** Pixel size of the SVG (square). */
  size?: number;
  /** Caption above the matrix. Pass "" to hide. */
  label?: string;
  /** Forwarded to AddressChip as the explorer link. */
  explorerHref?: string;
  className?: string;
  "aria-label"?: string;
}) {
  const [svg, setSvg] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    QRCodeLib.toString(value, {
      type: "svg",
      margin: 1,
      width: size,
      errorCorrectionLevel: "M",
      color: { dark: "#000000", light: "#ffffff" },
    })
      .then((raw) => {
        if (cancelled) return;
        // Only accept library SVG: never inject caller-controlled HTML.
        if (!raw.startsWith("<svg")) {
          setFailed(true);
          setSvg(null);
          return;
        }
        setFailed(false);
        setSvg(themeSvg(raw));
      })
      .catch(() => {
        if (cancelled) return;
        setFailed(true);
        setSvg(null);
      });
    return () => {
      cancelled = true;
    };
  }, [value, size]);

  return (
    <figure
      aria-label={ariaLabel ?? `QR code for ${value}`}
      className={cn(
        "inline-flex flex-col items-center gap-3 rounded-card border border-outline-variant bg-surface-container p-4 text-fg",
        className,
      )}
    >
      {label ? (
        <figcaption className="text-xs text-fg-muted">{label}</figcaption>
      ) : null}

      <div
        className="flex items-center justify-center text-fg"
        style={{ width: size, height: size }}
      >
        {failed ? (
          <p className="px-2 text-center text-xs text-sell">Couldn&apos;t render QR</p>
        ) : svg ? (
          // SVG is generated by `qrcode` from `value` (encoded as modules,
          // not interpolated into markup). Guarded by startsWith("<svg").
          <div
            className="[&>svg]:block [&>svg]:h-full [&>svg]:w-full"
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        ) : (
          <div
            aria-hidden="true"
            className="h-full w-full animate-pulse rounded-control bg-surface-bright"
          />
        )}
      </div>

      <AddressChip address={value} href={explorerHref} />
    </figure>
  );
}
